# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import catalog_pb2 as catalog__pb2


class CatalogStub(object):
    """The stock market service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LookUp = channel.unary_unary(
                '/catalog.Catalog/LookUp',
                request_serializer=catalog__pb2.StockName.SerializeToString,
                response_deserializer=catalog__pb2.StockDetails.FromString,
                )
        self.Update = channel.unary_unary(
                '/catalog.Catalog/Update',
                request_serializer=catalog__pb2.TradeDetails.SerializeToString,
                response_deserializer=catalog__pb2.SuccessMessage.FromString,
                )


class CatalogServicer(object):
    """The stock market service definition.
    """

    def LookUp(self, request, context):
        """Looks up a stock's value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Update the stock by performing trade
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LookUp': grpc.unary_unary_rpc_method_handler(
                    servicer.LookUp,
                    request_deserializer=catalog__pb2.StockName.FromString,
                    response_serializer=catalog__pb2.StockDetails.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=catalog__pb2.TradeDetails.FromString,
                    response_serializer=catalog__pb2.SuccessMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalog.Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Catalog(object):
    """The stock market service definition.
    """

    @staticmethod
    def LookUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/catalog.Catalog/LookUp',
            catalog__pb2.StockName.SerializeToString,
            catalog__pb2.StockDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/catalog.Catalog/Update',
            catalog__pb2.TradeDetails.SerializeToString,
            catalog__pb2.SuccessMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
