# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"\x1e\n\tStockName\x12\x11\n\tstockName\x18\x01 \x01(\t\"/\n\x0cStockDetails\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x10\n\x08quantity\x18\x02 \x01(\x05\":\n\x0cTradeDetails\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\t\n\x01N\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\"!\n\x0eSuccessMessage\x12\x0f\n\x07message\x18\x01 \x01(\x05\x32|\n\x07\x43\x61talog\x12\x35\n\x06LookUp\x12\x12.catalog.StockName\x1a\x15.catalog.StockDetails\"\x00\x12:\n\x06Update\x12\x15.catalog.TradeDetails\x1a\x17.catalog.SuccessMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOCKNAME._serialized_start=26
  _STOCKNAME._serialized_end=56
  _STOCKDETAILS._serialized_start=58
  _STOCKDETAILS._serialized_end=105
  _TRADEDETAILS._serialized_start=107
  _TRADEDETAILS._serialized_end=165
  _SUCCESSMESSAGE._serialized_start=167
  _SUCCESSMESSAGE._serialized_end=200
  _CATALOG._serialized_start=202
  _CATALOG._serialized_end=326
# @@protoc_insertion_point(module_scope)
