# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\":\n\x0cTradeDetails\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\t\n\x01N\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\"K\n\x0fResponseMessage\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x19\n\x11transactionNumber\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"\"\n\x0bOrderNumber\x12\x13\n\x0borderNumber\x18\x01 \x01(\x05\"V\n\x0cOrderDetails\x12\x13\n\x0borderNumber\x18\x01 \x01(\x05\x12\x11\n\tstockName\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"\x19\n\tLiveCheck\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"\x17\n\x07Success\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\";\n\rLeaderDetails\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\"7\n\tNewOrders\x12\x13\n\x0blatestOrder\x18\x01 \x01(\x05\x12\x15\n\rmissingOrders\x18\x02 \x01(\t2\xca\x02\n\x05Order\x12\x36\n\x05Trade\x12\x13.order.TradeDetails\x1a\x16.order.ResponseMessage\"\x00\x12\x35\n\x08GetOrder\x12\x12.order.OrderNumber\x1a\x13.order.OrderDetails\"\x00\x12*\n\x04Ping\x12\x10.order.LiveCheck\x1a\x0e.order.Success\"\x00\x12\x33\n\tSetLeader\x12\x14.order.LeaderDetails\x1a\x0e.order.Success\"\x00\x12\x37\n\x0ePropagateOrder\x12\x13.order.OrderDetails\x1a\x0e.order.Success\"\x00\x12\x38\n\x0e\x46\x65tchNewOrders\x12\x12.order.OrderNumber\x1a\x10.order.NewOrders\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRADEDETAILS._serialized_start=22
  _TRADEDETAILS._serialized_end=80
  _RESPONSEMESSAGE._serialized_start=82
  _RESPONSEMESSAGE._serialized_end=157
  _ORDERNUMBER._serialized_start=159
  _ORDERNUMBER._serialized_end=193
  _ORDERDETAILS._serialized_start=195
  _ORDERDETAILS._serialized_end=281
  _LIVECHECK._serialized_start=283
  _LIVECHECK._serialized_end=308
  _SUCCESS._serialized_start=310
  _SUCCESS._serialized_end=333
  _LEADERDETAILS._serialized_start=335
  _LEADERDETAILS._serialized_end=394
  _NEWORDERS._serialized_start=396
  _NEWORDERS._serialized_end=451
  _ORDER._serialized_start=454
  _ORDER._serialized_end=784
# @@protoc_insertion_point(module_scope)
